// =============================================================
// FILE: src/integrations/rtk/tags.ts
// RTK Query cache/tag listesi (konigsmassage modülleri)
// =============================================================

export const metahubTags = [
  'Auth',
  'User',
  'AdminUsers',
  'Profiles',
  'Profile',
  'UserRoles',
  'UserRole',
  'SiteSettings',
  'SiteSettingsBulk',
  'CustomPages',
  'CustomPageSlug',
  'CustomPage',
  'Faqs',
  'Services',
  'MenuItems',
  'MenuItem',
  'MenuItemPublic',
  'Slider',
  'Contacts',
  'EmailTemplates',
  'FooterSections',
  'Mail',
  'Newsletter',
  'Notifications',
  'Reviews',
  'Support',
  'Storage',
  'DbAdmin',
  'Sliders',
  'EmailTemplate',
  'Notification',
  'Review',
  'Health',
  'FooterSectionsBySlug',
  'AuditAuthEvent',
  'AuditRequestLog',
  'AuditMetric',
  'DbSnapshot',
  'DbAdmin',
  'DbModule',
  'DbManifest',
  'Bookings',
  'Booking',
  'BookingSlotAvailability',
  'BookingSlots',
  'BookingWorkingHours',
  'BookingWorkingHour',
  'BookingResources',
  'BookingResource',
  'AvailabilityWH',
  'AvailabilitySlots',
  'AvailabilityPlan',
  'AvailabilityCheck',
  'Resources',
  'ResourceWorkingHours',
  'ResourceWorkingHour',
  'WorkingHours',
  'WorkingHour',
  'WeeklyPlan',
  'ChatThreads',
  'ChatMessages',
  'ChatKnowledge',
] as const;

export type MetahubTag = (typeof metahubTags)[number];
